routes/web.php
<?php

use App\Http\Controllers\Admin\CartController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\CheckoutController;
use App\Http\Controllers\Admin\CustomerController;
use App\Http\Controllers\Admin\CustomerStatementController;
use App\Http\Controllers\Admin\CustomerWalletTransactionController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ItemController;
use App\Http\Controllers\Admin\ItemSalesReportController;
use App\Http\Controllers\Admin\KOTController;
use App\Http\Controllers\Admin\OrderBreakDownController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\OrderItemController;
use App\Http\Controllers\Admin\PaymentTypeController;
use App\Http\Controllers\Admin\ReportController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\StatusController;
use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

    return redirect()->route('dashboard');
});

Route::get('/dashboard',  [DashboardController::class, 'index'])->middleware('auth')->name('dashboard');
Route::post('/dashboard/getSalesData',  [DashboardController::class, 'getSalesChartData'])->middleware('auth')->name('admin.dashboard.getSalesData');


Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'auth'], function () {
    //User route
    Route::resource('users', UserController::class);
    Route::get('get-user-data', [UserController::class, 'getData'])->name('users.getData');
    Route::delete('users/force-delete/{user}', [UserController::class, 'forceDelete'])->name('users.forceDelete');
    Route::get('users/restore/{user}', [UserController::class, 'restore'])->name('users.restore');
    //Role route
    Route::resource('roles', RoleController::class);
    Route::get('get-role-data', [RoleController::class, 'getData'])->name('roles.getData');

    //Category route
    Route::get('get-category-data', [CategoryController::class, 'getData'])->name('categories.getData');
    Route::delete('categories/force-delete/{user}', [CategoryController::class, 'forceDelete'])->name('categories.forceDelete');
    Route::get('categories/restore/{user}', [CategoryController::class, 'restore'])->name('categories.restore');
    Route::post('categories/updateOrder', [CategoryController::class, 'updateOrder'])->name('category.updateOrder');
    Route::get('categories/changeStatus', [CategoryController::class, 'changeStatus'])->name('category.changeStatus');
    Route::resource('categories', CategoryController::class);

    //Item route
    Route::get('get-item-data', [ItemController::class, 'getData'])->name('items.getData');
    Route::delete('items/force-delete/{user}', [ItemController::class, 'forceDelete'])->name('items.forceDelete');
    Route::get('items/restore/{user}', [ItemController::class, 'restore'])->name('items.restore');
    Route::post('items/updateOrder', [ItemController::class, 'updateOrder'])->name('item.updateOrder');
    Route::get('items/changeStatus', [ItemController::class, 'changeStatus'])->name('item.changeStatus');
    Route::get('items/get-category-items-data', [ItemController::class, 'getCategoryItemsData'])->name('item.getCategoryItemsData');
    Route::resource('items', ItemController::class);

    //Status route
    Route::get('statuses', [StatusController::class, 'index'])->name('statuses.index');
    Route::put('statuses{status}', [StatusController::class, 'update'])->name('statuses.update');
    Route::get('statuses/{status}/edit', [StatusController::class, 'edit'])->name('statuses.edit');
    Route::get('get-status-data', [StatusController::class, 'getData'])->name('statuses.getData');

    //Order route
    Route::resource('orders', OrderController::class);
    Route::get('orders/add/{order}', [OrderController::class,'addMoreItem'])->name('orders.addItem');
    Route::put('orders/add/{order}', [OrderController::class,'updateMoreItem'])->name('orders.addItem.update');
    Route::get('get-order-data', [OrderController::class, 'getData'])->name('orders.getData');
    Route::get('get-order-detail', [OrderController::class, 'getOrderDetail'])->name('orders.getOrderDetail');
    //Order Breakdown controller
    // Route::get('orders/breakdown/{order}',[OrderBreakDownController::class,'index'])->name('orders.breakdown.index');
    Route::get('orders/breakdown/{order}',[OrderBreakDownController::class,'test'])->name('orders.breakdown.index');
    Route::post('orders/breakdown/{order}/test',[OrderBreakDownController::class,'store_test'])->name('orders.breakdown.store.test');
    // Route::post('orders/breakdown/{order}',[OrderBreakDownController::class,'store'])->name('orders.breakdown.store');

    //OrderItem Route
    Route::get('order_items/',[ OrderItemController::class,'index'])->name('order_items.index');
    Route::put('order_items/{order_item}',[ OrderItemController::class,'update'])->name('order_items.update');
    Route::delete('order_items/{order_item}',[ OrderItemController::class,'destory'])->name('order_items.delete');

    //Checkout Route
    Route::get('orders/checkout/{id}',[CheckoutController::class,'index'])->name('orders.checkout');
    Route::post('orders/checkout/{id}',[CheckoutController::class,'store'])->name('orders.checkout.store');


    //Cart route
    Route::get('get-cart-items', [CartController::class, 'getCartItems'])->name('cart.getCartItems');
    Route::get('add-cart-item', [CartController::class, 'addCartItem'])->name('cart.addCartItem');
    Route::get('remove-cart-item', [CartController::class, 'removeCartItem'])->name('cart.removeCartItem');
    Route::get('edit-cart-item-quantity', [CartController::class, 'editCartItemQuantity'])->name('cart.editCartItemQuantity');

    //Customer Controller
    Route::resource('customers', CustomerController::class);
    Route::get('get-customer-data', [CustomerController::class, 'getData'])->name('customer.getData');

    //Customer Wallet Transacton
    Route::get('customers/{customer}/wallet-transaction',[CustomerWalletTransactionController::class,'index'])->name('customers.wallet_transactions.index');
    Route::get('customers/{customer}/wallet-transaction/create',[CustomerWalletTransactionController::class,'create'])->name('customers.wallet_transactions.create');
    Route::post('customers/{customer}/wallet-transaction',[CustomerWalletTransactionController::class,'store'])->name('customers.wallet_transactions.store');

    Route::get('get-customer-wallet-transaction-data', [CustomerWalletTransactionController::class, 'getData'])->name('customers.wallet_transactions.getData');



    //Setting Controller
    Route::get('/settings',[SettingController::class,'create'])->name('settings.create');
    Route::post('/settings',[SettingController::class,'store'])->name('settings.store');



    //Report Controller
    Route::get('reports/sales',[ReportController::class,'index'])->name('reports.sales.index');
    Route::get('get-sales-report-data', [ReportController::class, 'getSalesData'])->name('reports.salesData');
    Route::get('export-sales-report-data', [ReportController::class, 'exportSales'])->name('reports.exportSales');

    //ItemSalesReport Controller
    Route::get('reports/item-sales',[ItemSalesReportController::class,'index'])->name('reports.item_sales.index');
    Route::get('get-item-sales-report-data', [ItemSalesReportController::class, 'getItemSalesData'])->name('reports.itemSalesData');
    Route::get('export-item-sales-report-data', [ItemSalesReportController::class, 'exportSales'])->name('reports.exportItemSales');

    //Customer Statement Controller
    Route::get('reports/customer-statement',[CustomerStatementController::class,'index'])->name('reports.customer_statement');
    //KOT Controller
    Route::get('kot',[KOTController::class,'index'])->name('kot.index');
    Route::post('complete-order-item',[KOTController::class,'completeOrderItem'])->name('kot.completeOrderItem');
    Route::get('get-order-data-for-kot', [KOTController::class, 'getData'])->name('kot.getData');
    Route::get('get-order-detail-for-kot', [KOTController::class, 'getOrderDetail'])->name('kot.getOrderDetail');

    //Payment Type Controller
    Route::get('payment-types',[PaymentTypeController::class,'index'])->name('payment_types.index');
    Route::get('payment-types/changeStatus', [PaymentTypeController::class, 'changeStatus'])->name('payment_types.changeStatus');

});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
//Invoice Controller
Route::get('/order/invoice/{order}', [App\Http\Controllers\InvoiceController::class, 'index'])->name('orders.getBill');

app/Models/Customer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    use HasFactory;
    protected $table = 'table_customers';

    protected $fillable = ['name', 'phone_no'];

    public function setNameAttribute($value)
    {
        $this->attributes['name'] = strtolower($value);
    }

    public function getNameAttribute($name)
    {
        return  ucwords($name);
    }

    /**
     * Get all of the cusomter_wallet_transaction for the Customer
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function cusomter_wallet_transactions()
    {
        return $this->hasMany(CustomerWalletTransaction::class, 'customer_id');
    }

    public function last_transaction()
    {
        return $this->hasOne(CustomerWalletTransaction::class)->latestOfMany()->withDefault([
            'current_amount'=>0,
        ]);;

    }

    public function getWalletBalanceAttribute()
    {
        if($this->cusomter_wallet_transactions()->count())
        {
            return $this->cusomter_wallet_transactions()->latest()->first()->current_amount;
        }else{
            return 0;
        }
    }

    public function wallet_balance()
    {
        if($this->cusomter_wallet_transactions()->count())
        {
            return $this->cusomter_wallet_transactions()->latest()->first()->current_amount;
        }else{
            return 0;
        }
    }
}

app/Http/Controllers/Admin/CustomerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreCustomerRequest;
use App\Http\Requests\Admin\UpdateCustomerRequest;
use App\Models\Customer;
use App\Models\Order;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Yajra\DataTables\Facades\DataTables;

class CustomerController extends Controller
{
    private $title = null;

    public function __construct()
    {
        $this->middleware('permission:customer_list|customer_create|customer_edit|customer_delete', ['only' => ['index','show','getData']]);
        $this->middleware('permission:customer_create', ['only' => ['create','store']]);
        $this->title = 'Customer Management';
    }
    public function index(Request $request)
    {
        $title = $this->title;
        $breadcrumbs =[ 'Customer'=>route('admin.customers.index')];
        return view('admin.customers.index', compact('title','breadcrumbs'));
    }

    public function create()
    {
        $title = $this->title;
        $breadcrumbs =[ 'Customer'=>route('admin.customers.index'),'Create'=>'#'];

        return view('admin.customers.create', compact('title','breadcrumbs'));

    }

    public function store(StoreCustomerRequest $request)
    {

        Customer::create([
            'name' => $request->name,
            'phone_no'=> $request->phone_no,
        ]);
        if(isset($request->new))
        {
            return redirect()->route('admin.customers.create')->with("success", "Customer saved successfully");

        }else{
            return redirect()->route('admin.customers.index')->with("success", "Customer saved successfully");

        }
    }

    public function edit(Customer $customer)
    {
        $title = $this->title;
        $breadcrumbs =[ 'Customer'=>route('admin.customers.index'),'Edit'=>'#'];

        return view('admin.customers.edit', compact('title','customer','breadcrumbs'));

    }

    public function update(UpdateCustomerRequest $request, Customer $customer)
    {
        $customer->name =$request->name;
        $customer->phone_no =$request->phone_no;
        $customer->save();
        return redirect()->route('admin.customers.index')->with("success", "Customer updated successfully");
    }

    public function show(Customer $customer)
    {
        $title = $this->title;
        $breadcrumbs =[ 'Customer'=>route('admin.customers.index'), 'Show'=>'#'];


       return view('admin.customers.show',compact('title','customer','breadcrumbs'));
    }

    public function wallet_transaction($id)
    {
        $customer =Customer::findOrFail($id);
        $title = $this->title;
        $breadcrumbs =[ 'Customer'=>route('admin.customers.index'), 'Wallet Transaction'=>'#'];
        return view('admin.customers.wallet_transaction',compact('customer','title','breadcrumbs'));
    }

    public function getData(Request $request)
    {
        if ($request->ajax()) {
            $data = Customer::select('table_customers.*')->with('last_transaction');
            // $da= DB::select("Select table_customers.*,table_customer_wallet_transactions.current_amount from table_customers LEFT JOIN table_customer_wallet_transactions
            // ON table_customers.id = table_customer_wallet_transactions.customer_id and table_customer_wallet_transactions.id IN (select MAX(a2.id) from table_customer_wallet_transactions as a2 join table_customers as u2 on u2.id = a2.customer_id group by u2.id)");
            $canEdit = auth()->user()->can('customer_edit');
            // return DataTables::of($da)->addColumn(
            //             'action',
            //             function ($row)use ($canEdit) {
            //                 $editBtn = $canEdit? '<a href="'.route('admin.customers.edit', $row->id).'"
            //                 class="btn btn-xs btn-warning"><i class="fa fa-pencil-alt"></i></a>':'';
            //                 $showBtn ='<a href="'.route('admin.customers.show', $row->id).'"
            //                 class="btn btn-xs btn-info"><i class="fa fa-eye"></i></a>';
            //                 $walletTransactionBtn = '<a href="'.route('admin.customers.wallet_transactions.index',$row->id).'"
            //                 class="btn btn-xs btn-primary">Wallet History</a>';
            //                 return $showBtn.' '.$walletTransactionBtn.' '.$editBtn;
            //             })->make(true);
            return DataTables::of($data)
                ->editColumn('created_at', function (Customer $status) {
                    return [
                        'display' => $status->created_at->diffForHumans(),
                        'timestamp' => $status->created_at
                    ];
                })

                ->addColumn(
                    'action',
                    function ($row)use ($canEdit) {
                        $editBtn = $canEdit? '<a href="'.route('admin.customers.edit', $row->id).'"
                        class="btn btn-xs btn-warning"><i class="fa fa-pencil-alt"></i></a>':'';
                        $showBtn ='<a href="'.route('admin.customers.show', $row->id).'"
                        class="btn btn-xs btn-info"><i class="fa fa-eye"></i></a>';
                        $walletTransactionBtn = '<a href="'.route('admin.customers.wallet_transactions.index',$row->id).'"
                        class="btn btn-xs btn-primary">Wallet History</a>';
                        return $showBtn.' '.$walletTransactionBtn.' '.$editBtn;
                    }
                )
                ->make(true);
        }
    }
}

resources/views/admin/customers/create.blade.php
@extends('layouts.admin.master')

@section('content')
    <div class="row">
        <div class="col">
            <div class="card card-outline card-success ">
                <div class="card-header">
                    <h2 class="card-title">Add Customer</h2>
                    <div class="card-tools">
                        <a class="btn btn-primary" href="{{ route('admin.customers.index') }}"> Back</a></i></a>
                    </div>
                </div>
                <div class="card-body ">
                    <form method="POST" action="{{ route('admin.customers.store') }}">
                        @csrf
                        <div class="row">
                            <div class="form-group col-md-6">
                                <label class="label" for="name">Customer Name</label>
                                <input type="text" name="name" value="{{ old('name') }}"
                                    class="form-control  @error('name') is-invalid @enderror" autocomplete="off"
                                    placeholder="Enter Customer Name" required>
                                @error('name')
                                    <span class=" text-danger" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="form-group col-md-6">
                                <label class="label" for="phone_no">Contact No.</label>
                                <input type="text" name="phone_no" value="{{ old('phone_no') }}"
                                    class="form-control  @error('phone_no') is-invalid @enderror" autocomplete="off"
                                    placeholder="Enter phone_no" required>
                                @error('phone_no')
                                    <span class=" text-danger" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="col-md-12 text-center">
                            <button type="submit" name="new" value="1" class="btn btn-primary  mt-3">Save and
                                Create</button>
                            <button type="submit" class="btn btn-primary  mt-3">Save and exit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('js')
    <script>
        $(function() {
            $('.my-colorpicker2').colorpicker();
            $('.my-colorpicker2').on('colorpickerChange', function(event) {
                $('.my-colorpicker2 .fa-square').css('color', event.color.toString());
            });
        });
    </script>
@endsection

resources/views/admin/customers/edit.blade.php
@extends('layouts.admin.master')

@section('content')
    <div class="row">
        <div class="col">
            <div class="card card-outline card-success ">
                <div class="card-header">
                    <h2 class="card-title">Edit Customer</h2>
                    <div class="card-tools">
                        <a class="btn btn-primary" href="{{ route('admin.customers.index') }}"> Back</a></i></a>
                    </div>
                </div>
                <div class="card-body ">
                    <form method="POST" action="{{ route('admin.customers.update',$customer->id) }}">
                        @csrf
                        @method('PUT')
                        <div class="row">
                            <div class="form-group col-md-6">
                                <label class="label" for="name">Customer Name</label>
                                <input type="text" name="name" value="{{ old('name')?:$customer->name }}"
                                    class="form-control  @error('name') is-invalid @enderror" autocomplete="off"
                                    placeholder="Enter Customer Name" required>
                                @error('name')
                                    <span class=" text-danger" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="form-group col-md-6">
                                <label class="label" for="phone_no">Contact No.</label>
                                <input type="text" name="phone_no" value="{{ old('phone_no')?:$customer->phone_no }}"
                                    class="form-control  @error('phone_no') is-invalid @enderror" autocomplete="off"
                                    placeholder="Enter phone_no" required>
                                @error('phone_no')
                                    <span class=" text-danger" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="col-md-12 text-center">
                            <button type="submit" class="btn btn-primary  mt-3">Edit Customer</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('js')
    <script>
        $(function() {
            $('.my-colorpicker2').colorpicker();
            $('.my-colorpicker2').on('colorpickerChange', function(event) {
                $('.my-colorpicker2 .fa-square').css('color', event.color.toString());
            });
        });
    </script>
@endsection

resources/views/admin/customers/show.blade.php
@extends('layouts.admin.master')

@section('content')
    <div class="row">
        <div class="col">
            <div class="card card-outline card-dark">
                <div class="card-header">
                    <h2 class="card-title">Customer History</h2>
                </div>
                <div class="card-body table-responsive">
                    <table class="table table-bordered" id="table">
                        <thead>
                            <th>Id</th>
                            <th>Bill No</th>
                            <th>Table No</th>
                            <th>Discount</th>
                            <th>Total</th>
                            <th>Created At</th>
                            <th>Status</th>
                            <th>Action</th>
                        </thead>
                        <tbody id="tablecontents">

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        @include('admin.orders._orderDetailModal')
    </div>
@endsection
@section('js')
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    <script>
        $(document).ready(function() {
            // $('#table').DataTable({
            //     "aaSorting": []
            // });
            var table = $('#table').DataTable({
                responsive: true,
                processing: true,
                serverSide: true,
                order: [
                    [5, 'desc']
                ],
                ajax: {
                    url: "{{ route('admin.orders.getData') }}",
                    data: function(d) {
                        d.mode = 'history',
                            d.customer_id = {{ $customer->id }};

                    }
                },
                columns: [{
                        data: 'id',
                        name: 'id'
                    },
                    {
                        data: 'bill_no',
                        name: 'bill_no'
                    },
                    {
                        data: 'table_no',
                        name: 'table_no',
                    },
                    {
                        data: 'discount',
                        name: 'discount'
                    },
                    {
                        data: 'total',
                        name: 'total'
                    },
                    {
                        data: 'created_at',
                        name: 'created_at',
                        render: {
                            _: 'display',
                            sort: 'timestamp'
                        },
                        searchable: false

                    },
                    {
                        data: 'status',
                        name: 'status',
                        render: function(data) {
                            return '<i class="badge text-sm" style="background-color:' + data
                                .color + '">' + data.title + '</i>';
                        },
                        searchable: false,
                    },
                    {
                        data: 'action',
                        name: 'action',
                        orderable: false,
                        searchable: false
                    }
                ]

            });


            $(document).on('change', '#mode', function() {
                table.draw();
            });



            $(document).on('click', '.get-detail', function() {
                let order_id = $(this).attr('rel');
                $('#modal-lg').modal('toggle');
                $('.get-detail').attr('disabled', true);

                clearModal();

                $.ajax({
                    type: 'GET',
                    url: '{{ route('admin.orders.getOrderDetail') }}',
                    data: {
                        'order_id': order_id
                    },
                    beforeSend: function() {
                        $('#overlay').show();
                    },
                    success: function(data) {
                        if (data.status === 'success') {
                            setModalData(data.order);
                            $('#get-bill').attr('href', data.billRoute);

                            data.orderItems.forEach(function(item) {
                                $('#table-items').append(template(item.item.name, item
                                    .total, item.price));
                            });
                            if (data.order.discount && data.order.discount !=0 ) {
                                $('#table-items').append(
                                    "<tr><td colspan='3'>Discount</td><td>" +
                                    foramtValue(data.order.discount) + "</td></tr>");
                            }
                            if (data.order.service_charge) {
                                $('#table-items').append(
                                    "<tr><td colspan='3'>Service Charge</td><td>" +
                                    foramtValue(data.order.service_charge) + "</td></tr>");
                            }
                            if (data.order.tax) {
                                $('#table-items').append(
                                    "<tr><td colspan='3'>Tax</td><td>" +
                                    foramtValue(data.order.tax) + "</td></tr>");
                            }

                            if (data.order.net_total) {
                                $('#table-items').append(
                                    "<tr><td colspan='3'>Net Total</td><td>" +
                                    foramtValue(data.order.net_total) + "</td></tr>");
                            }else{
                                $('#table-items').append(
                                    "<tr><td colspan='3'>Total</td><td>" +
                                    foramtValue(data.order.total) + "</td></tr>");
                            }

                        } else {
                            console.log('false');
                        }
                        $('#overlay').hide();
                        $('.get-detail').attr('disabled', false);


                    },
                    error: function(xhr) {

                        $('#overlay').hide();
                        $('.get-detail').attr('disabled', false);
                        console.log('Internal Serve Error');
                    }
                });
            });


        });

        function template(name, total_quantity, price) {

            return '<tr><td>' + name + '</td><td>' + total_quantity + '</td><td>Rs. ' +
                price + '</td><td>Rs. ' +
                price * total_quantity + '</td><</tr>';
        }

        function clearModal() {
            $('#bill-no').html('');
            $('#customer-name').html('');
            $('#customer-contact').html('');
            $('#order-date').html('');
            $('#order-status').html('');
            $('#table-items').html('');
            $('#get-bill').attr('href', 'javascript:void(0)');
            $('#paymentType').css('display', 'none');


        }

        function setModalData(order) {
            $('#bill-no').html(order.bill_no);
            $('#customer-name').html(order.customer.name);
            $('#customer-contact').html(order.customer.phone_no);
            $('#order-date').html(order.order_datetime);
            $('#order-status').html(order.status.title);
            if (order.payment_type_id) {
                $('#paymentType').css('display', 'block');
                $('#payment-type').html(order.payment_type.name);
            }

        }

        function foramtValue(val) {
            return 'Rs. ' + val;
        }
    </script>
@endsection