routes/web.php
<?php

use App\Http\Controllers\Admin\CartController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\CheckoutController;
use App\Http\Controllers\Admin\CustomerController;
use App\Http\Controllers\Admin\CustomerStatementController;
use App\Http\Controllers\Admin\CustomerWalletTransactionController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ItemController;
use App\Http\Controllers\Admin\ItemSalesReportController;
use App\Http\Controllers\Admin\KOTController;
use App\Http\Controllers\Admin\OrderBreakDownController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\OrderItemController;
use App\Http\Controllers\Admin\PaymentTypeController;
use App\Http\Controllers\Admin\ReportController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\StatusController;
use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

    return redirect()->route('dashboard');
});

Route::get('/dashboard',  [DashboardController::class, 'index'])->middleware('auth')->name('dashboard');
Route::post('/dashboard/getSalesData',  [DashboardController::class, 'getSalesChartData'])->middleware('auth')->name('admin.dashboard.getSalesData');


Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'auth'], function () {
    //User route
    Route::resource('users', UserController::class);
    Route::get('get-user-data', [UserController::class, 'getData'])->name('users.getData');
    Route::delete('users/force-delete/{user}', [UserController::class, 'forceDelete'])->name('users.forceDelete');
    Route::get('users/restore/{user}', [UserController::class, 'restore'])->name('users.restore');
    //Role route
    Route::resource('roles', RoleController::class);
    Route::get('get-role-data', [RoleController::class, 'getData'])->name('roles.getData');

    //Category route
    Route::get('get-category-data', [CategoryController::class, 'getData'])->name('categories.getData');
    Route::delete('categories/force-delete/{user}', [CategoryController::class, 'forceDelete'])->name('categories.forceDelete');
    Route::get('categories/restore/{user}', [CategoryController::class, 'restore'])->name('categories.restore');
    Route::post('categories/updateOrder', [CategoryController::class, 'updateOrder'])->name('category.updateOrder');
    Route::get('categories/changeStatus', [CategoryController::class, 'changeStatus'])->name('category.changeStatus');
    Route::resource('categories', CategoryController::class);

    //Item route
    Route::get('get-item-data', [ItemController::class, 'getData'])->name('items.getData');
    Route::delete('items/force-delete/{user}', [ItemController::class, 'forceDelete'])->name('items.forceDelete');
    Route::get('items/restore/{user}', [ItemController::class, 'restore'])->name('items.restore');
    Route::post('items/updateOrder', [ItemController::class, 'updateOrder'])->name('item.updateOrder');
    Route::get('items/changeStatus', [ItemController::class, 'changeStatus'])->name('item.changeStatus');
    Route::get('items/get-category-items-data', [ItemController::class, 'getCategoryItemsData'])->name('item.getCategoryItemsData');
    Route::resource('items', ItemController::class);

    //Status route
    Route::get('statuses', [StatusController::class, 'index'])->name('statuses.index');
    Route::put('statuses{status}', [StatusController::class, 'update'])->name('statuses.update');
    Route::get('statuses/{status}/edit', [StatusController::class, 'edit'])->name('statuses.edit');
    Route::get('get-status-data', [StatusController::class, 'getData'])->name('statuses.getData');

    //Order route
    Route::resource('orders', OrderController::class);
    Route::get('orders/add/{order}', [OrderController::class,'addMoreItem'])->name('orders.addItem');
    Route::put('orders/add/{order}', [OrderController::class,'updateMoreItem'])->name('orders.addItem.update');
    Route::get('get-order-data', [OrderController::class, 'getData'])->name('orders.getData');
    Route::get('get-order-detail', [OrderController::class, 'getOrderDetail'])->name('orders.getOrderDetail');
    //Order Breakdown controller
    // Route::get('orders/breakdown/{order}',[OrderBreakDownController::class,'index'])->name('orders.breakdown.index');
    Route::get('orders/breakdown/{order}',[OrderBreakDownController::class,'test'])->name('orders.breakdown.index');
    Route::post('orders/breakdown/{order}/test',[OrderBreakDownController::class,'store_test'])->name('orders.breakdown.store.test');
    // Route::post('orders/breakdown/{order}',[OrderBreakDownController::class,'store'])->name('orders.breakdown.store');

    //OrderItem Route
    Route::get('order_items/',[ OrderItemController::class,'index'])->name('order_items.index');
    Route::put('order_items/{order_item}',[ OrderItemController::class,'update'])->name('order_items.update');
    Route::delete('order_items/{order_item}',[ OrderItemController::class,'destory'])->name('order_items.delete');

    //Checkout Route
    Route::get('orders/checkout/{id}',[CheckoutController::class,'index'])->name('orders.checkout');
    Route::post('orders/checkout/{id}',[CheckoutController::class,'store'])->name('orders.checkout.store');


    //Cart route
    Route::get('get-cart-items', [CartController::class, 'getCartItems'])->name('cart.getCartItems');
    Route::get('add-cart-item', [CartController::class, 'addCartItem'])->name('cart.addCartItem');
    Route::get('remove-cart-item', [CartController::class, 'removeCartItem'])->name('cart.removeCartItem');
    Route::get('edit-cart-item-quantity', [CartController::class, 'editCartItemQuantity'])->name('cart.editCartItemQuantity');

    //Customer Controller
    Route::resource('customers', CustomerController::class);
    Route::get('get-customer-data', [CustomerController::class, 'getData'])->name('customer.getData');

    //Customer Wallet Transacton
    Route::get('customers/{customer}/wallet-transaction',[CustomerWalletTransactionController::class,'index'])->name('customers.wallet_transactions.index');
    Route::get('customers/{customer}/wallet-transaction/create',[CustomerWalletTransactionController::class,'create'])->name('customers.wallet_transactions.create');
    Route::post('customers/{customer}/wallet-transaction',[CustomerWalletTransactionController::class,'store'])->name('customers.wallet_transactions.store');

    Route::get('get-customer-wallet-transaction-data', [CustomerWalletTransactionController::class, 'getData'])->name('customers.wallet_transactions.getData');



    //Setting Controller
    Route::get('/settings',[SettingController::class,'create'])->name('settings.create');
    Route::post('/settings',[SettingController::class,'store'])->name('settings.store');



    //Report Controller
    Route::get('reports/sales',[ReportController::class,'index'])->name('reports.sales.index');
    Route::get('get-sales-report-data', [ReportController::class, 'getSalesData'])->name('reports.salesData');
    Route::get('export-sales-report-data', [ReportController::class, 'exportSales'])->name('reports.exportSales');

    //ItemSalesReport Controller
    Route::get('reports/item-sales',[ItemSalesReportController::class,'index'])->name('reports.item_sales.index');
    Route::get('get-item-sales-report-data', [ItemSalesReportController::class, 'getItemSalesData'])->name('reports.itemSalesData');
    Route::get('export-item-sales-report-data', [ItemSalesReportController::class, 'exportSales'])->name('reports.exportItemSales');

    //Customer Statement Controller
    Route::get('reports/customer-statement',[CustomerStatementController::class,'index'])->name('reports.customer_statement');
    //KOT Controller
    Route::get('kot',[KOTController::class,'index'])->name('kot.index');
    Route::post('complete-order-item',[KOTController::class,'completeOrderItem'])->name('kot.completeOrderItem');
    Route::get('get-order-data-for-kot', [KOTController::class, 'getData'])->name('kot.getData');
    Route::get('get-order-detail-for-kot', [KOTController::class, 'getOrderDetail'])->name('kot.getOrderDetail');

    //Payment Type Controller
    Route::get('payment-types',[PaymentTypeController::class,'index'])->name('payment_types.index');
    Route::get('payment-types/changeStatus', [PaymentTypeController::class, 'changeStatus'])->name('payment_types.changeStatus');

});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
//Invoice Controller
Route::get('/order/invoice/{order}', [App\Http\Controllers\InvoiceController::class, 'index'])->name('orders.getBill');

app/Http/Controllers/Admin/KOTController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Order;
use App\Models\OrderItem;
use App\Models\Status;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;

class KOTController extends Controller
{
    private $title = null;

    public function __construct()
    {
        $this->middleware('permission:order_item_edit', ['only' => ['edit', 'update',]]);
        $this->title = 'KOT';
    }
    public function index()
    {
        $title = $this->title;
        $breadcrumbs = ['Order' => route('admin.kot.index')];

        return view('admin.kot.index', compact('title', 'breadcrumbs'));
    }


    public function getData(Request $request)
    {

        if ($request->ajax()) {

            $processingStatus = Status::where('title', 'processing')->first()->id;
            switch ($request->mode) {
                case ('all'):
                    $today = Carbon::today();
                    $data = Order::select('*')->with('customer:id,name')->with('status:id,title,color');
                    break;
                case ('completed'):
                    $today = Carbon::today();
                    $data = Order::select('*')->with('customer:id,name')->with('status:id,title,color')->where('status_id', 3);

                case ('processing'):
                    $today = Carbon::today();
                    $data = Order::select('*')->with('customer:id,name')->with('status:id,title,color')->where('status_id', 1);
                    break;
            }

            return DataTables::of($data)
                ->editColumn('created_at', function ($order) {
                    return [
                        'display' => $order->created_at->diffForHumans(),
                        'timestamp' => $order->created_at
                    ];
                })->addColumn(
                    'action',
                    function ($row, Request $request) use ($processingStatus) {

                            $detail = '<button rel="' . $row->id . '"  class="btn btn-primary btn-xs get-detail my-2"><i class="fa fa-eye"></i></button>';
                            return  $detail;
                    }
                )->orderColumn('status', function ($query, $order) {
                    $query->orderBy('status_id', $order);
                })->orderColumn('price', function ($query, $order) {
                    $query->orderBy('price', $order);
                })
                ->rawColumns(['action'])
                ->make(true);
        }
    }

    public function getOrderDetail(Request $request)
    {
        if (request()->ajax()) {
            $order = Order::with('status:id,title')->with('customer:id,name,phone_no')->where('id', $request->order_id)->first();
            $orderItems = OrderItem::with('item:id,name')->where('order_id', $order->id)->where('total', '>', 0)->get()->groupBy('order_no');
            $billRoute = route('orders.getBill',$order->id);

            if ($order) {
                return response()->json([
                    'order' => $order,
                    'billRoute' => $billRoute,
                    'orderItems' => $orderItems,
                    'status' => 'success',
                    'message' => 'Order fetched successfully',
                ]);
            } else {
                return response()->json([
                    'status' => 'fail',
                    'message' => 'No Order found',
                ]);
            }
        }
    }
}

resources/views/admin/kot/_orderDetailModal.blade.php
<div class="modal fade" id="modal-lg">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="overlay" id="overlay" style="display: none">
                <i class="fas fa-2x fa-sync fa-spin"></i>
            </div>
            <div class="modal-header">
                <h4 class="modal-title">Order Detail</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <div class="row">
                    <div class="col-12">
                        <b>Bill No</b>: <b id="bill-no"></b>
                    </div>
                    <div class="col-12">
                        <b>Customer Name</b>: <b id="customer-name"></b>
                    </div>
                    <div class="col-12">
                        <b>Customer Contact</b>: <b id="customer-contact"></b>
                    </div>
                    <div class="col-12" id="talbeNO">
                        <b>Table No</b>: <b id="table-no"></b>
                    </div>
                    <div class="col-12" id="orderDate">
                        <b>Order Date</b>: <b id="order-date"></b>
                    </div>
                    <div class="col-12">
                        <b>Status</b>: <b id="order-status"></b>
                    </div>

                </div>
                <div class="row mt-4" id="ordered-tems">

                </div>
            </div>
            <div class="modal-footer justify-content-end">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

resources/views/admin/kot/index.blade.php
@extends('layouts.admin.master')

@section('content')
    <div class="row">
        <div class="col">
            <div class="card card-outline card-dark">
                <div class="card-header">
                    <h2 class="card-title">Order List</h2>
                    <div class="card-tools form-inline">
                        <select id="mode" class="form-control ">
                            <option value="all">All</option>
                            <option value="processing">Processing</option>
                            <option value="completed">Complete</option>
                        </select>
                        @can('order_create')
                            <a class="btn btn-success ml-3" href="{{ route('admin.orders.create') }}"> <i
                                    class="fa fa-plus"></i></a>
                        @endcan
                    </div>
                </div>
                <div class="card-body table-responsive">
                    <table class="table table-bordered table-sm" id="table">
                        <thead>
                            <th>Id</th>
                            <th>Bill No</th>
                            <th>Customer Name</th>
                            <th>Table No</th>
                            <th>Created At</th>
                            <th>Status</th>
                            <th>Action</th>
                        </thead>
                        <tbody id="tablecontents">

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        @include('admin.kot._orderDetailModal')
    </div>
@endsection
@section('js')
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    <script>
        $(document).ready(function() {
            // $('#table').DataTable({
            //     "aaSorting": []
            // });
            var table = $('#table').DataTable({
                responsive: true,
                processing: true,
                serverSide: true,
                order: [
                    [0, 'desc']
                ],
                ajax: {
                    url: "{{ route('admin.kot.getData') }}",
                    data: function(d) {
                        d.mode = $('#mode').val();
                    }
                },
                columns: [{
                        data: 'id',
                        name: 'id'
                    },
                    {
                        data: 'bill_no',
                        name: 'bill_no'
                    },
                    {
                        data: 'customer',
                        name: 'customer',
                        render: function($data) {
                            return $data.name;
                        },

                    },
                    {
                        data: 'table_no',
                        name: 'table_no',
                    },
                    {
                        data: 'created_at',
                        name: 'created_at',
                        render: {
                            _: 'display',
                            sort: 'timestamp'
                        },
                        searchable: false

                    },
                    {
                        data: 'status',
                        name: 'status',
                        render: function(data) {
                            return '<i class="badge text-sm" style="background-color:' + data
                                .color + '">' + data.title + '</i>';
                        },
                        searchable: false,
                    },
                    {
                        data: 'action',
                        name: 'action',
                        orderable: false,
                        searchable: false
                    }
                ]

            });


            $(document).on('change', '#mode', function() {
                table.draw();
            });

            //for delete btn
            $(document).on('click', '.btn-delete', function(e) {
                e.preventDefault();
                let form = $(this);
                Swal.fire({
                    title: 'Are you sure?',
                    text: "Do you want to  delete item?",
                    icon: 'danger',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes!'
                }).then((result) => {
                    if (result.isConfirmed) {
                        $(this).closest("form").submit();
                    }
                });
            });

            $(document).on('click', '.get-detail', function() {
                let order_id = $(this).attr('rel');
                $('#modal-lg').modal('toggle');
                $('.get-detail').attr('disabled', true);

                clearModal();

                $.ajax({
                    type: 'GET',
                    url: '{{ route('admin.kot.getOrderDetail') }}',
                    data: {
                        'order_id': order_id
                    },
                    beforeSend: function() {
                        $('#overlay').show();
                    },
                    success: function(data) {
                        $('#overlay').hide();
                        $('.get-detail').attr('disabled', false);

                        if (data.status === 'success') {
                            setModalData(data.order);
                            $('#get-bill').attr('href', data.billRoute);
                            for (let key in data.orderItems) {

                                $('#ordered-tems').append(template(data.orderItems[key],key));
                            }

                        } else {
                            console.log('false');
                        }


                    },
                    error: function(xhr) {

                        $('#overlay').hide();
                        $('.get-detail').attr('disabled', false);
                        console.log('Internal Serve Error');
                    }
                });
            });

        });

        $(document).on('click', '.complete-order-item', function() {
            let btn = $(this);
            let item_id = btn.attr('rel');
            $.ajax({
                type: "POST",
                dataType: "json",
                url: "{{ route('admin.kot.completeOrderItem') }}",
                data: {
                    item_id: item_id,
                    "_token": "{{ csrf_token() }}",
                },
                success: function(response) {
                    if (response.status == "success") {
                        btn.closest('td').html('Completed');
                    } else {
                        console.log(response);
                    }
                }
            });
        });

        $(document).on('click','.print-this',function(){
            let key= $(this).attr('rel');
            $('#talbeNO, #orderDate, #order-list-'+key).printThis({
                header: "<h1>KOT Slip</h1>",
                importCSS: true,
                printDelay: 1000,

            });
        });

        function template(items,key) {
            let template ='<div class="col-6"><h5>Order Slip '+key
                +'</h5> </div> <div class="col-6"> <a href="javascript:void(0);" rel="'+key+'" class="btn btn-primary btn-xs print-this float-right ">Print This</a> </div> <div class="col-12"> <table class="table table-sm" id="order-list-'+
                    key+'"> <thead> <th>Item Name</th> <th>Quantity</th> </thead> <tbody> ';
            items.forEach(function(value) {
                template +='<tr><td>'+value.item.name+'</td><td>'+value.total+'</td></tr>';
            });
            template+='</tbody></table></div>';
            return template;

        }

        function clearModal() {
            $('#bill-no').html('');
            $('#customer-name').html('');
            $('#customer-contact').html('');
            $('#order-date').html('');
            $('#order-status').html('');
            $('#ordered-tems').html('');
            $('#get-bill').attr('href', 'javascript:void(0)');
            $('#table-no').html('');


        }

        function setModalData(order) {
            $('#bill-no').html(order.bill_no);
            $('#customer-name').html(order.customer.name);
            $('#customer-contact').html(order.customer.phone_no);
            $('#order-date').html(order.order_datetime);
            $('#order-status').html(order.status.title);
            $('#table-no').html(order.table_no);


        }


        function foramtValue(val) {
            return 'Rs. ' + val;
        }
    </script>
@endsection