routes/web.php
<?php

use App\Http\Controllers\Admin\CartController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\CheckoutController;
use App\Http\Controllers\Admin\CustomerController;
use App\Http\Controllers\Admin\CustomerStatementController;
use App\Http\Controllers\Admin\CustomerWalletTransactionController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ItemController;
use App\Http\Controllers\Admin\ItemSalesReportController;
use App\Http\Controllers\Admin\KOTController;
use App\Http\Controllers\Admin\OrderBreakDownController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\OrderItemController;
use App\Http\Controllers\Admin\PaymentTypeController;
use App\Http\Controllers\Admin\ReportController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\StatusController;
use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

    return redirect()->route('dashboard');
});

Route::get('/dashboard',  [DashboardController::class, 'index'])->middleware('auth')->name('dashboard');
Route::post('/dashboard/getSalesData',  [DashboardController::class, 'getSalesChartData'])->middleware('auth')->name('admin.dashboard.getSalesData');


Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'auth'], function () {
    //User route
    Route::resource('users', UserController::class);
    Route::get('get-user-data', [UserController::class, 'getData'])->name('users.getData');
    Route::delete('users/force-delete/{user}', [UserController::class, 'forceDelete'])->name('users.forceDelete');
    Route::get('users/restore/{user}', [UserController::class, 'restore'])->name('users.restore');
    //Role route
    Route::resource('roles', RoleController::class);
    Route::get('get-role-data', [RoleController::class, 'getData'])->name('roles.getData');

    //Category route
    Route::get('get-category-data', [CategoryController::class, 'getData'])->name('categories.getData');
    Route::delete('categories/force-delete/{user}', [CategoryController::class, 'forceDelete'])->name('categories.forceDelete');
    Route::get('categories/restore/{user}', [CategoryController::class, 'restore'])->name('categories.restore');
    Route::post('categories/updateOrder', [CategoryController::class, 'updateOrder'])->name('category.updateOrder');
    Route::get('categories/changeStatus', [CategoryController::class, 'changeStatus'])->name('category.changeStatus');
    Route::resource('categories', CategoryController::class);

    //Item route
    Route::get('get-item-data', [ItemController::class, 'getData'])->name('items.getData');
    Route::delete('items/force-delete/{user}', [ItemController::class, 'forceDelete'])->name('items.forceDelete');
    Route::get('items/restore/{user}', [ItemController::class, 'restore'])->name('items.restore');
    Route::post('items/updateOrder', [ItemController::class, 'updateOrder'])->name('item.updateOrder');
    Route::get('items/changeStatus', [ItemController::class, 'changeStatus'])->name('item.changeStatus');
    Route::get('items/get-category-items-data', [ItemController::class, 'getCategoryItemsData'])->name('item.getCategoryItemsData');
    Route::resource('items', ItemController::class);

    //Status route
    Route::get('statuses', [StatusController::class, 'index'])->name('statuses.index');
    Route::put('statuses{status}', [StatusController::class, 'update'])->name('statuses.update');
    Route::get('statuses/{status}/edit', [StatusController::class, 'edit'])->name('statuses.edit');
    Route::get('get-status-data', [StatusController::class, 'getData'])->name('statuses.getData');

    //Order route
    Route::resource('orders', OrderController::class);
    Route::get('orders/add/{order}', [OrderController::class,'addMoreItem'])->name('orders.addItem');
    Route::put('orders/add/{order}', [OrderController::class,'updateMoreItem'])->name('orders.addItem.update');
    Route::get('get-order-data', [OrderController::class, 'getData'])->name('orders.getData');
    Route::get('get-order-detail', [OrderController::class, 'getOrderDetail'])->name('orders.getOrderDetail');
    //Order Breakdown controller
    // Route::get('orders/breakdown/{order}',[OrderBreakDownController::class,'index'])->name('orders.breakdown.index');
    Route::get('orders/breakdown/{order}',[OrderBreakDownController::class,'test'])->name('orders.breakdown.index');
    Route::post('orders/breakdown/{order}/test',[OrderBreakDownController::class,'store_test'])->name('orders.breakdown.store.test');
    // Route::post('orders/breakdown/{order}',[OrderBreakDownController::class,'store'])->name('orders.breakdown.store');

    //OrderItem Route
    Route::get('order_items/',[ OrderItemController::class,'index'])->name('order_items.index');
    Route::put('order_items/{order_item}',[ OrderItemController::class,'update'])->name('order_items.update');
    Route::delete('order_items/{order_item}',[ OrderItemController::class,'destory'])->name('order_items.delete');

    //Checkout Route
    Route::get('orders/checkout/{id}',[CheckoutController::class,'index'])->name('orders.checkout');
    Route::post('orders/checkout/{id}',[CheckoutController::class,'store'])->name('orders.checkout.store');


    //Cart route
    Route::get('get-cart-items', [CartController::class, 'getCartItems'])->name('cart.getCartItems');
    Route::get('add-cart-item', [CartController::class, 'addCartItem'])->name('cart.addCartItem');
    Route::get('remove-cart-item', [CartController::class, 'removeCartItem'])->name('cart.removeCartItem');
    Route::get('edit-cart-item-quantity', [CartController::class, 'editCartItemQuantity'])->name('cart.editCartItemQuantity');

    //Customer Controller
    Route::resource('customers', CustomerController::class);
    Route::get('get-customer-data', [CustomerController::class, 'getData'])->name('customer.getData');

    //Customer Wallet Transacton
    Route::get('customers/{customer}/wallet-transaction',[CustomerWalletTransactionController::class,'index'])->name('customers.wallet_transactions.index');
    Route::get('customers/{customer}/wallet-transaction/create',[CustomerWalletTransactionController::class,'create'])->name('customers.wallet_transactions.create');
    Route::post('customers/{customer}/wallet-transaction',[CustomerWalletTransactionController::class,'store'])->name('customers.wallet_transactions.store');

    Route::get('get-customer-wallet-transaction-data', [CustomerWalletTransactionController::class, 'getData'])->name('customers.wallet_transactions.getData');



    //Setting Controller
    Route::get('/settings',[SettingController::class,'create'])->name('settings.create');
    Route::post('/settings',[SettingController::class,'store'])->name('settings.store');



    //Report Controller
    Route::get('reports/sales',[ReportController::class,'index'])->name('reports.sales.index');
    Route::get('get-sales-report-data', [ReportController::class, 'getSalesData'])->name('reports.salesData');
    Route::get('export-sales-report-data', [ReportController::class, 'exportSales'])->name('reports.exportSales');

    //ItemSalesReport Controller
    Route::get('reports/item-sales',[ItemSalesReportController::class,'index'])->name('reports.item_sales.index');
    Route::get('get-item-sales-report-data', [ItemSalesReportController::class, 'getItemSalesData'])->name('reports.itemSalesData');
    Route::get('export-item-sales-report-data', [ItemSalesReportController::class, 'exportSales'])->name('reports.exportItemSales');

    //Customer Statement Controller
    Route::get('reports/customer-statement',[CustomerStatementController::class,'index'])->name('reports.customer_statement');
    //KOT Controller
    Route::get('kot',[KOTController::class,'index'])->name('kot.index');
    Route::post('complete-order-item',[KOTController::class,'completeOrderItem'])->name('kot.completeOrderItem');
    Route::get('get-order-data-for-kot', [KOTController::class, 'getData'])->name('kot.getData');
    Route::get('get-order-detail-for-kot', [KOTController::class, 'getOrderDetail'])->name('kot.getOrderDetail');

    //Payment Type Controller
    Route::get('payment-types',[PaymentTypeController::class,'index'])->name('payment_types.index');
    Route::get('payment-types/changeStatus', [PaymentTypeController::class, 'changeStatus'])->name('payment_types.changeStatus');

});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
//Invoice Controller
Route::get('/order/invoice/{order}', [App\Http\Controllers\InvoiceController::class, 'index'])->name('orders.getBill');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Storage;

class Category extends Model
{
    use HasFactory,SoftDeletes;

    protected $table ='table_categories';
    protected $fillable = ['title','order','status','image'];

    public function image()
    {
        return (Storage::disk('public')->exists($this->image)) ? '/storage/' . $this->image : asset('noimgavialable.png');
    }

    public function items()
    {
        return $this->hasMany(Item::class);
    }
    public function setTitlesAttribute($value)
    {
        $this->attributes['title'] = strtolower($value);
    }

    public function getTitlesAttribute($title)
    {
        return  ucwords($title);
    }

    protected static function boot() {
        parent::boot();

        static::deleting(function($category) {
            $category->items()->delete();
        });

        static::restoring(function($category) {
            $category->items()->restore();
        });
    }
}

resources/views/admin/categories/create.blade.php
@extends('layouts.admin.master')

@section('content')
    <div class="row">
        <div class="col">
            <div class="card card-outline card-success ">
                <div class="card-header">
                    <h2 class="card-title">Add Category</h2>
                    <div class="card-tools">
                        <a class="btn btn-primary" href="{{ route('admin.categories.index') }}"> Back</a></i></a>
                    </div>
                </div>
                <div class="card-body ">
                    <form method="POST" action="{{ route('admin.categories.store') }}" enctype="multipart/form-data">
                        @csrf
                        <div class="row">
                            <div class="form-group col-md-6">
                                <label class="label" for="title">Category Name</label>
                                <input type="text" name="title" value="{{ old('title') }}"
                                    class="form-control  @error('title') is-invalid @enderror" minlength="3"
                                    placeholder="Enter Name" required autocomplete="off">
                                @error('title')
                                    <span class=" text-danger" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="form-group col-md-6">
                                <label class="label" for="title">Status</label>
                                <div class="custom-control custom-switch  ">
                                    <input type="checkbox" value="1" class="custom-control-input" name="status"
                                        id="status">
                                    <label class="custom-control-label" for="status">Active</label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group ml-n2">
                            <div class="col-md-6">
                                <label for="exampleInputFile">Upload Image</label>
                                <div class="input-group ">
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" name="image" id="image"
                                            required>
                                        <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                                    </div>
                                    @error('image')
                                        <span class=" text-danger" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-md-6  p-t-2">
                                <img id="preview-image-before-upload" src="{{ asset('noimgavialable.png') }}"
                                    width="150">
                            </div>
                        </div>
                        <div class="col-md-12 text-center">
                            <button type="submit" name="new" value="1" class="btn btn-primary  mt-3">Save and
                                Create</button>
                            <button type="submit" class="btn btn-primary  mt-3">Save and exit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('js')
    <script type="text/javascript">
        $(document).ready(function(e) {
            bsCustomFileInput.init();

            $('#image').change(function() {

                let reader = new FileReader();

                reader.onload = (e) => {

                    $('#preview-image-before-upload').attr('src', e.target.result);
                }

                reader.readAsDataURL(this.files[0]);

            });

        });
    </script>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.admin.master')

@section('content')
    <div class="row">
        <div class="col">
            <div class="card card-outline card-warning ">
                <div class="card-header">
                    <h2 class="card-title ">Edit Category</h2>
                    <div class="card-tools">
                        <a class="btn btn-primary" href="{{ route('admin.categories.index') }}"> Back</a></i></a>
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST" action="{{ route('admin.categories.update', $category->id) }}"
                        enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="row">
                            <div class="form-group col-md-6">
                                <label class="label" for="title">Category Name</label>
                                <input type="text" name="title" value="{{ old('title') ?: $category->title }}"
                                    class="form-control  @error('title') is-invalid @enderror" minlength="3"
                                    placeholder="Enter title" required autocomplete="off">
                                @error('title')
                                    <span class=" text-danger" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="form-group col-md-6">
                                <label class="label" for="order">Category Order</label>
                                <input type="number" min="0" step="1" name="order"
                                    value="{{ old('order') ?: $category->order }}"
                                    class="form-control  @error('order') is-invalid @enderror" placeholder="Enter order"
                                    required>
                                @error('order')
                                    <span class=" text-danger" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>

                        </div>
                        <div class="form-group ml-n2">
                            <div class="col-md-6">
                                <label for="exampleInputFile">Upload Image</label>
                                <div class="input-group ">
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" name="image" id="image">
                                        <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                                    </div>
                                    @error('image')
                                        <span class=" text-danger" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-md-6 p-t-2">
                                <img id="preview-image-before-upload" src="{{ $category->image() }}" width="150">
                            </div>
                        </div>
                        <div class="col-md-12 text-center">
                            <button type="submit" class="btn btn-primary  mt-3">Edit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('js')
    <script type="text/javascript">
        $(document).ready(function(e) {
            bsCustomFileInput.init();

            $('#image').change(function() {

                let reader = new FileReader();

                reader.onload = (e) => {

                    $('#preview-image-before-upload').attr('src', e.target.result);
                }

                reader.readAsDataURL(this.files[0]);

            });

        });
    </script>
@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.admin.master')

@section('content')
    <div class="row">
        <div class="col">
            <div class="card card-outline card-dark">
                <div class="card-header">
                    <h2 class="card-title">Category List</h2>
                    <div class="card-tools form-inline">
                        @can('category_delete')
                            <select id="mode" class="form-control">
                                <option value="0">List</option>
                                <option value="1">Deleted</option>
                            </select>
                        @endcan
                        @can('category_create')
                            <a class="btn btn-success ml-3" href="{{ route('admin.categories.create') }}"> <i
                                    class="fa fa-plus"></i></a>
                        @endcan
                    </div>
                </div>
                <div class="card-body  table-responsive">
                    <table class="table table-bordered" id="table">
                        <thead>
                            <th>Id</th>
                            <th>Name</th>
                            <th>Status</th>
                            <th>Image</th>
                            <th>Created At</th>
                            <th>Action</th>
                        </thead>
                        <tbody id="tablecontents">

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('js')
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    <script>
        $(document).ready(function() {
            // $('#table').DataTable({
            //     "aaSorting": []
            // });
            var table = $('#table').DataTable({
                responsive: true,
                processing: true,
                serverSide: true,
                "aaSorting": [],
                ajax: {
                    url: "{{ route('admin.categories.getData') }}",
                    data: function(d) {
                        d.mode = $('#mode').val();
                    }
                },
                columns: [{
                        data: 'id',
                        name: 'id'
                    },
                    {
                        data: 'title',
                        name: 'title'
                    },
                    {
                        data: 'status',
                        name: 'status',

                    },
                    {
                        data: 'image',
                        name: 'image',
                        render: function(data) {
                            return '<img width="120px" height="100px" src="' + data + '"></img>';
                        },
                        searchable: false,
                        orderable: false,

                    },
                    {
                        data: 'created_at',
                        name: 'created_at',
                        render:{
                            _:'display',
                            sort:'timestamp'
                        },
                        searchable: false

                    },
                    {
                        data: 'action',
                        name: 'action',
                        orderable: false,
                        searchable: false
                    },
                ]

            });

            //for sortable table
            $("#tablecontents").sortable({
                items: "tr",
                cursor: 'move',
                opacity: 0.6,
                update: function() {
                    sendOrderToServer();
                }
            });


            //To change order while changing table
            function sendOrderToServer() {
                var order = [];
                $('tr.row1').each(function(index, element) {
                    order.push({
                        id: $(this).attr('data-id'),
                        position: index + 1
                    });
                });
                $.ajax({
                    type: "POST",
                    dataType: "json",
                    url: "{{ route('admin.category.updateOrder') }}",
                    data: {
                        order: order,
                        "_token": "{{ csrf_token() }}",
                    },
                    success: function(response) {
                        if (response.status == "success") {
                            console.log(response);
                        } else {
                            console.log(response);
                        }
                    }
                });
            }
            $(document).on('change', '#mode', function() {
                table.draw();
            });

            //for delete btn
            $(document).on('click', '.btn-delete', function(e) {
                e.preventDefault();
                let form = $(this);
                Swal.fire({
                    title: 'Are you sure?',
                    text: "Do you want to  delete category?",
                    icon: 'danger',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes!'
                }).then((result) => {
                    if (result.isConfirmed) {
                        $(this).closest("form").submit();
                    }
                });
            });

            //for changing status
            $(document).on('click', '.changeStatus', function(e) {
                e.preventDefault();
                let btn = $(this).closest('[type=checkbox]');
                Swal.fire({
                    title: 'Are you sure?',
                    text: "Do you want to change category status?",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes!'
                }).then((result) => {
                    if (result.isConfirmed) {
                        let category_id = btn.data('id');
                        let status = ($(this).is(":checked")) ? 0 : 1;
                        let clickedBtn = btn;
                        $.ajax({
                            type: "GET",
                            url: '{{ route('admin.category.changeStatus') }}',
                            data: {
                                'status': status,
                                'category_id': category_id
                            },
                            success: function(res) {
                                if (res.success) {
                                    btn.parent().find('label').text(res.status).trigger(
                                        'change');
                                    btn.prop('checked', res.checked);
                                } else {
                                    Swal.fire('Something went wrong!');
                                }
                            },
                            error: function() {
                                alert('Internal Server Error !');
                            }
                        });
                    }
                });

            });
        });
    </script>
@endsection